name = "TaraKernel"
uuid = "71c599f0-fb9f-429e-b654-e07d545af317"
version = "0.1.0"
authors = ["josePereiro <jose.pereiro.lab@gmail.com> and contributors"]

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
JSON = "1.3.0"
OrderedCollections = "1.8.1"
Random = "1.11.0"
SHA = "0.7.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
